{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import psycopg2\n",
    "from psycopg2 import sql\n",
    "from psycopg2 import Error"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "DB_HOST = 'pavlov.ing.puc.cl'\n",
    "DB_PORT = '22'\n",
    "DB_USER = 'grupo64'\n",
    "DB_PASSWORD = 'grupo64'\n",
    "DB_NAME = 'grupo64e2'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error de conexión o durante la operación en la base de datos: connection to server at \"pavlov.ing.puc.cl\" (146.155.13.56), port 22 failed: server closed the connection unexpectedly\n",
      "\tThis probably means the server terminated abnormally\n",
      "\tbefore or while processing the request.\n",
      "SSL SYSCALL error: Connection reset by peer (0x00002746/10054)\n",
      "connection to server at \"pavlov.ing.puc.cl\" (146.155.13.56), port 22 failed: expected authentication request from server, but received S\n",
      "\n"
     ]
    }
   ],
   "source": [
    "\n",
    "# Ruta del archivo CSV\n",
    "archivo_csv = '../datos e2/clientes.csv'\n",
    "\n",
    "# Configuración de la conexión\n",
    "try:\n",
    "    conexion = psycopg2.connect(\n",
    "        dbname=DB_NAME,\n",
    "        user=DB_USER,\n",
    "        password=DB_PASSWORD,\n",
    "        host=DB_HOST,\n",
    "        port=DB_PORT\n",
    "    )\n",
    "    print(conexion)\n",
    "    # Crear un cursor\n",
    "    cursor = conexion.cursor()\n",
    "    print(cursor)\n",
    "\n",
    "    # Crear la tabla (ajusta esto según tu esquema de datos)\n",
    "    crear_tabla_query = \"\"\"\n",
    "    CREATE TABLE IF NOT EXISTS clientes (\n",
    "        nombre varchar   NOT NULL,\n",
    "        email varchar   NOT NULL,\n",
    "        telefono varchar   NOT NULL,\n",
    "        clave varchar       NOT NULL,\n",
    "        direccion varchar   NOT NULL,\n",
    "        comuna varchar    NOT NULL,\n",
    "        CONSTRAINT pk_Cliente PRIMARY KEY (\n",
    "            email))\n",
    "    \"\"\"\n",
    "    cursor.execute(crear_tabla_query)\n",
    "    conexion.commit()\n",
    "\n",
    "    # Preparar el query de inserción\n",
    "    insercion_query = \"\"\"\n",
    "    INSERT INTO clientes (nombre, email, telefono, clave, direccion, comuna)\n",
    "    VALUES (%s, %s, %s, %s, %s, %s);\n",
    "    \"\"\"\n",
    "\n",
    "    # Leer y procesar el archivo CSV\n",
    "    with open(archivo_csv, 'r') as file:\n",
    "        # Leer la primera línea para obtener los nombres de las columnas\n",
    "        columnas = file.readline().strip().split(',')\n",
    "\n",
    "        # Iterar sobre cada línea en el archivo CSV\n",
    "        for linea in file:\n",
    "            # Dividir la línea en valores\n",
    "            valores = linea.strip().split(',')\n",
    "\n",
    "            try:\n",
    "                cursor.execute(insercion_query, (nombre, email, telefono, clave, direccion, comuna))\n",
    "            except Error as e:\n",
    "                    print(f\"Error al insertar la línea {linea}: {e}\")\n",
    "                    conexion.rollback()\n",
    "                    continue\n",
    "\n",
    "    # Confirmar la inserción\n",
    "    conexion.commit()\n",
    "\n",
    "except Error as e:\n",
    "    print(f\"Error de conexión o durante la operación en la base de datos: {e}\")\n",
    "\n",
    "# finally:\n",
    "\n",
    "#     if cursor:\n",
    "#         cursor.close()\n",
    "#     if conexion:\n",
    "#         conexion.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "ename": "OperationalError",
     "evalue": "connection to server at \"pavlov.ing.puc.cl\" (146.155.13.56), port 22 failed: server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\nSSL SYSCALL error: Connection reset by peer (0x00002746/10054)\nconnection to server at \"pavlov.ing.puc.cl\" (146.155.13.56), port 22 failed: expected authentication request from server, but received S\n",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mOperationalError\u001b[0m                          Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[9], line 1\u001b[0m\n\u001b[1;32m----> 1\u001b[0m conexion \u001b[38;5;241m=\u001b[39m \u001b[43mpsycopg2\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mconnect\u001b[49m\u001b[43m(\u001b[49m\n\u001b[0;32m      2\u001b[0m \u001b[43m        \u001b[49m\u001b[43mdbname\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mDB_NAME\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m      3\u001b[0m \u001b[43m        \u001b[49m\u001b[43muser\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mDB_USER\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m      4\u001b[0m \u001b[43m        \u001b[49m\u001b[43mpassword\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mDB_PASSWORD\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m      5\u001b[0m \u001b[43m        \u001b[49m\u001b[43mhost\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mDB_HOST\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m      6\u001b[0m \u001b[43m        \u001b[49m\u001b[43mport\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mDB_PORT\u001b[49m\n\u001b[0;32m      7\u001b[0m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m      8\u001b[0m \u001b[38;5;28mprint\u001b[39m(conexion)\n\u001b[0;32m      9\u001b[0m \u001b[38;5;66;03m# Crear un cursor\u001b[39;00m\n",
      "File \u001b[1;32mc:\\Python312\\Lib\\site-packages\\psycopg2\\__init__.py:122\u001b[0m, in \u001b[0;36mconnect\u001b[1;34m(dsn, connection_factory, cursor_factory, **kwargs)\u001b[0m\n\u001b[0;32m    119\u001b[0m     kwasync[\u001b[38;5;124m'\u001b[39m\u001b[38;5;124masync_\u001b[39m\u001b[38;5;124m'\u001b[39m] \u001b[38;5;241m=\u001b[39m kwargs\u001b[38;5;241m.\u001b[39mpop(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124masync_\u001b[39m\u001b[38;5;124m'\u001b[39m)\n\u001b[0;32m    121\u001b[0m dsn \u001b[38;5;241m=\u001b[39m _ext\u001b[38;5;241m.\u001b[39mmake_dsn(dsn, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs)\n\u001b[1;32m--> 122\u001b[0m conn \u001b[38;5;241m=\u001b[39m \u001b[43m_connect\u001b[49m\u001b[43m(\u001b[49m\u001b[43mdsn\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mconnection_factory\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mconnection_factory\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mkwasync\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    123\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m cursor_factory \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[0;32m    124\u001b[0m     conn\u001b[38;5;241m.\u001b[39mcursor_factory \u001b[38;5;241m=\u001b[39m cursor_factory\n",
      "\u001b[1;31mOperationalError\u001b[0m: connection to server at \"pavlov.ing.puc.cl\" (146.155.13.56), port 22 failed: server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\nSSL SYSCALL error: Connection reset by peer (0x00002746/10054)\nconnection to server at \"pavlov.ing.puc.cl\" (146.155.13.56), port 22 failed: expected authentication request from server, but received S\n"
     ]
    }
   ],
   "source": [
    "conexion = psycopg2.connect(\n",
    "        dbname=DB_NAME,\n",
    "        user=DB_USER,\n",
    "        password=DB_PASSWORD,\n",
    "        host=DB_HOST,\n",
    "        port=DB_PORT\n",
    "    )\n",
    "print(conexion)\n",
    "# Crear un cursor\n",
    "cursor = conexion.cursor()\n",
    "print(cursor)\n",
    "\n",
    "# Crear la tabla (ajusta esto según tu esquema de datos)\n",
    "crear_tabla_query = \"\"\"\n",
    "CREATE TABLE IF NOT EXISTS clientes (\n",
    "    nombre varchar   NOT NULL,\n",
    "    email varchar   NOT NULL,\n",
    "    telefono varchar   NOT NULL,\n",
    "    clave varchar       NOT NULL,\n",
    "    direccion varchar   NOT NULL,\n",
    "    comuna varchar    NOT NULL,\n",
    "    CONSTRAINT pk_Cliente PRIMARY KEY (\n",
    "        email))\n",
    "\"\"\"\n",
    "cursor.execute(crear_tabla_query)\n",
    "conexion.commit()\n",
    "\n",
    "# Preparar el query de inserción\n",
    "insercion_query = \"\"\"\n",
    "INSERT INTO clientes (nombre, email, telefono, clave, direccion, comuna)\n",
    "VALUES (%s, %s, %s, %s, %s, %s);\n",
    "\"\"\"\n",
    "\n",
    "# Leer y procesar el archivo CSV\n",
    "with open(archivo_csv, 'r') as file:\n",
    "    # Leer la primera línea para obtener los nombres de las columnas\n",
    "    columnas = file.readline().strip().split(',')\n",
    "\n",
    "    # Iterar sobre cada línea en el archivo CSV\n",
    "    for linea in file:\n",
    "        # Dividir la línea en valores\n",
    "        valores = linea.strip().split(',')\n",
    "\n",
    "        try:\n",
    "            cursor.execute(insercion_query, (nombre, email, telefono, clave, direccion, comuna))\n",
    "        except Error as e:\n",
    "                print(f\"Error al insertar la línea {linea}: {e}\")\n",
    "                conexion.rollback()\n",
    "                continue\n",
    "\n",
    "# Confirmar la inserción\n",
    "conexion.commit()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
